name: core_services
description: Core services package for fines_plus
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  flutter_local_notifications: ^19.4.0
  
  firebase_core: ^4.0.0
  uuid: ^4.5.1



flutter:
  uses-material-design: true
