name: fines_plus
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.6+40

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  core_repository:
    path: packages/core_repository
  cupertino_icons: ^1.0.8
  
  core_cubit:
    path: packages/core_cubit
  core_localization:
    path: packages/core_localization
  core_utils:
    path: packages/core_utils
  core:
    path: packages/core
  core_data:
    path: packages/core_data
  core_services:
    path: packages/core_services
  design_system:
    path: packages/design_system 
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  excel: ^4.0.6
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  auto_route: ^10.1.0+1
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  envied: ^1.1.1
  sojo_link: ^0.1.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  http: ^1.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  g_recaptcha_v3: ^1.0.0
  html: ^0.15.6
  google_mobile_ads: ^6.0.0
  font_awesome_flutter: ^10.10.0
  fl_chart: ^1.0.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0
  firebase_dynamic_links: ^6.1.10
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^5.5.0
  firebase_auth: ^5.7.0
  app_links: ^6.4.1
  flutter_easy_recaptcha_v2: ^0.1.0
  flutter_inappwebview: ^6.1.5
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.9
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  webview_flutter: ^4.13.0
  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2
  flutter_secure_storage: ^9.2.4
  location: ^8.0.1
  flutter_web_auth_2: ^4.1.0
  flutter_svg: ^2.2.1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4
  file_picker: ^10.3.3
  equatable: ^2.0.7
  get_it: ^8.2.0
  bloc: ^9.0.1
  in_app_purchase: ^3.2.3
  flutter_facebook_auth: ^7.1.2
  sign_in_with_apple: ^7.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  introduction_screen: ^3.1.12
  rxdart: ^0.28.0
  percent_indicator: ^4.2.3
  flutter_dotenv: ^6.0.0
  in_app_purchase_android: ^0.4.0+8

     



dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.0.0
  flutter_lints: ^5.0.0


  build_runner: ^2.4.0
  freezed: ^3.1.0
  json_serializable: ^6.8.0

  auto_route_generator: ^10.2.3
  envied_generator: ^1.1.1


flutter:


  uses-material-design: true
  
  assets:
    - assets/config/autolux.json
    - assets/config/fastcar.json
    - assets/icons/map.png
    - assets/icons/google_logo.png
    - assets/icons/logo_app.png
    - assets/icons/insurance.png
    - assets/icons/car-wash.svg
    - assets/icons/no_ad.svg
    - assets/icons/tuning.jpg
    - assets/icons/battery.png
    - assets/icons/brake.png
    - assets/icons/chassis.png
    - assets/icons/conditioning.png
    - assets/icons/cooling_radiator.png
    - assets/icons/muffler.png
    - assets/icons/oil_service.png
    - assets/icons/transmission.jpg
    - assets/icons/wheels.png
    - assets/fonts/Fines/Roboto-Regular.ttf
    - assets/images/cars/tesla_model_x_red.png
    - assets/images/insurance_bg.png
    - assets/images/fines_bg.png
    - assets/images/analytics_bg.png
    - assets/images/maintenance_bg.png
    - assets/icons/insurance.png
    - assets/icons/finance.png
    - assets/icons/coin_stack.png
    - assets/icons/steeringWheel.png
    - assets/config/.env
   
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_app.png"
flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/logo_app.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
dependency_overrides:
  freezed: 3.1.1
  freezed_annotation: 3.1.1
