name: fines_plus
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  core_repository:
    path: packages/core_repository
  cupertino_icons: ^1.0.8
  
  core_cubit:
    path: packages/core_cubit
  core_localization:
    path: packages/core_localization
  core_utils:
    path: packages/core_utils
  core:
    path: packages/core
  core_data:
    path: packages/core_data
  core_services:
    path: packages/core_services
  webview_feature:
    path: packages/features/webview
  design_system:
    path: packages/design_system 
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2


  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  auto_route: ^10.1.0+1
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  envied: ^1.1.1
  sojo_link: ^0.1.0
  uuid: ^4.5.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  http: ^1.5.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  g_recaptcha_v3: ^1.0.0
  html: ^0.15.6
  google_mobile_ads: ^6.0.0
  font_awesome_flutter: ^10.10.0
  fl_chart: ^1.0.0
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0
  firebase_dynamic_links: ^6.1.10
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^5.5.0
  firebase_auth: ^5.7.0
  app_links: ^6.4.1
  flutter_easy_recaptcha_v2: ^0.1.0
  flutter_inappwebview: ^6.1.5
  firebase_analytics: ^11.6.0
  firebase_crashlytics: ^4.3.9
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  webview_flutter: ^4.13.0
  google_sign_in: 6.1.5
  url_launcher: ^6.3.2
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.0.0
 
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  auto_route_generator: ^10.2.3
  envied_generator: ^1.1.1

flutter:


  uses-material-design: true
  
  assets:
    - assets/config/autolux.json
    - assets/config/fastcar.json
    - assets\icons\map.png
    - assets/fonts/Fines/Roboto-Regular.ttf
  
