class ServiceItem {
  final String name;
  final double priceUSD;
  ServiceItem({required this.name, required this.priceUSD});
}

class ServiceList {
  static final items = <ServiceItem>[
    ServiceItem(name: "ДВС - діагностика (огляд, вимір компресії)", priceUSD: 25),
    ServiceItem(name: "ДВС - зняття/установка (заміна)", priceUSD: 275),
    ServiceItem(name: "ДВС - капітальний ремонт", priceUSD: 450),
    ServiceItem(name: "Прокладка клапанної кришки - заміна", priceUSD: 20),
    ServiceItem(name: "Прокладка ГБЦ - заміна", priceUSD: 240),
    ServiceItem(name: "Прокладка піддону картера - заміна", priceUSD: 40),
    ServiceItem(name: "Ремінь приводний - заміна", priceUSD: 21),
    ServiceItem(name: "Ролик приводного ременя - заміна", priceUSD: 15),
    ServiceItem(name: "Ремкомплект ГРМ - заміна", priceUSD: 90),
    ServiceItem(name: "Інжектор - чистка (без урахування спецрідини)", priceUSD: 36),
    ServiceItem(name: "Заміна олії ДВС", priceUSD: 12),
    ServiceItem(name: "Заміна повітряного фільтра ДВС", priceUSD: 7.5),
    ServiceItem(name: "Заміна салонного фільтра", priceUSD: 10.5),
    ServiceItem(name: "Чистка дросельної заслінки", priceUSD: 30),
    ServiceItem(name: "Комп'ютерна діагностика", priceUSD: 21),
    ServiceItem(name: "Ремонт електропроводки та електроустаткування", priceUSD: 11),
    ServiceItem(name: "Ремонт генераторів", priceUSD: 30),
    ServiceItem(name: "Ремонт стартерів", priceUSD: 30),
    ServiceItem(name: "Заміна кисневого датчика (лямбда-зонд)", priceUSD: 18),
    ServiceItem(name: "Діагностика та ремонт блоків ЕБУ двигуна", priceUSD: 15),
    ServiceItem(name: "Заміна ламп у протитуманних фарах", priceUSD: 2),
    ServiceItem(name: "Встановлення ксенону", priceUSD: 22),
    ServiceItem(name: "Діагностика комплексна (без урахування комп'ютерної діагностики)", priceUSD: 30),
    ServiceItem(name: "Комплексна діагностика", priceUSD: 60),
    ServiceItem(name: "Система кондиціювання - діагностика та заправка", priceUSD: 26),
    ServiceItem(name: "Паливна система - діагностика (вимір тиску)", priceUSD: 15),
    ServiceItem(name: "Діагностика підвіски", priceUSD: 9),
    ServiceItem(name: "Ремонт важелів підвіски", priceUSD: 30),
    ServiceItem(name: "Заміна амортизаторів", priceUSD: 43),
    ServiceItem(name: "Заміна передніх амортизаторів", priceUSD: 72),
    ServiceItem(name: "Заміна задніх амортизаторів", priceUSD: 60),
    ServiceItem(name: "Заміна відбійника амортизатора", priceUSD: 43),
    ServiceItem(name: "Заміна опорного підшипника амортизатора", priceUSD: 43),
    ServiceItem(name: "Заміна пружин амортизаторів", priceUSD: 43),
    ServiceItem(name: "Заміна пильника заднього амортизатора", priceUSD: 43),
    ServiceItem(name: "Ремонт пневмопідвіски", priceUSD: 60),
    ServiceItem(name: "Заміна стійок стабілізатора", priceUSD: 24),
    ServiceItem(name: "Заміна втулок стабілізатора", priceUSD: 24),
    ServiceItem(name: "Заміна кульових опор", priceUSD: 21),
    ServiceItem(name: "Заміна підшипників маточок", priceUSD: 42),
    ServiceItem(name: "Заміна сайлентблоків підвіски", priceUSD: 12),
    ServiceItem(name: "Схід-розвал", priceUSD: 32),
    ServiceItem(name: "Ходова частина - діагностика", priceUSD: 12),
    ServiceItem(name: "Стійки стабілізатора - заміна", priceUSD: 24),
    ServiceItem(name: "Втулки стабілізатора - заміна", priceUSD: 24),
    ServiceItem(name: "Шарова опора - заміна", priceUSD: 21),
    ServiceItem(name: "Наконечник рульової тяги - заміна", priceUSD: 12),
    ServiceItem(name: "Рульова тяга - заміна", priceUSD: 15),
    ServiceItem(name: "Амортизатори підвіски (передня вісь) - заміна", priceUSD: 72),
    ServiceItem(name: "Амортизатори підвіски (задня вісь) - заміна", priceUSD: 60),
    ServiceItem(name: "Ступиця колеса - заміна", priceUSD: 36),
    ServiceItem(name: "Підшипник маточини колеса - заміна", priceUSD: 42),
    ServiceItem(name: "Рульова рейка - ремонт", priceUSD: 60),
    ServiceItem(name: "Важіль підвіски - заміна", priceUSD: 30),
    ServiceItem(name: "Сайлентблок важеля підвіски - заміна (при знятому важелі)", priceUSD: 12),
    ServiceItem(name: "Пильовик ШРУС (зовнішній) - заміна", priceUSD: 30),
    ServiceItem(name: "Пильовик ШРУС (внутрішній) - заміна", priceUSD: 48),
    ServiceItem(name: "ШРУС приводного валу - заміна", priceUSD: 48),
    ServiceItem(name: "Привідний вал - заміна", priceUSD: 48),
    ServiceItem(name: "Поліровка кузова", priceUSD: 96),
    ServiceItem(name: "Поліровка фар", priceUSD: 18),
    ServiceItem(name: "Предпродажна хімчистка салону", priceUSD: 60),
    ServiceItem(name: "Перепродажне полірування кузова", priceUSD: 120),
    ServiceItem(name: "Чистка сидінь автомобіля", priceUSD: 18),
    ServiceItem(name: "Хімчистка салону", priceUSD: 120),
    ServiceItem(name: "Покриття керамікою", priceUSD: 8),
    ServiceItem(name: "Видалення дрібних подряпин", priceUSD: 6),
    ServiceItem(name: "Заміна гальмівних колодок", priceUSD: 15),
    ServiceItem(name: "Заміна гальмівних дисків", priceUSD: 60),
    ServiceItem(name: "Заміна гальмівної рідини", priceUSD: 24),
    ServiceItem(name: "Заміна гальмівних шлангів", priceUSD: 15),
    ServiceItem(name: "Ремонт гальмівних супортів", priceUSD: 17),
    ServiceItem(name: "Профілактика гальмівних механізмів", priceUSD: 9),
    ServiceItem(name: "Ремонт кермових рейок", priceUSD: 60),
    ServiceItem(name: "Заміна наконечників рульових тяг", priceUSD: 12),
    ServiceItem(name: "Заміна рульових тяг", priceUSD: 15),
    ServiceItem(name: "Заміна хрестовини рульового валу", priceUSD: 22),
    ServiceItem(name: "Діагностика та ремонт ДВС", priceUSD: 24),
    ServiceItem(name: "Заміна прокладки клапанної кришки", priceUSD: 21),
    ServiceItem(name: "Заміна прокладки ГБЦ", priceUSD: 240),
    ServiceItem(name: "Заміна прокладки піддону картера", priceUSD: 39),
    ServiceItem(name: "Заміна сальника коленвала", priceUSD: 26),
    ServiceItem(name: "Професійний ремонт ГРМ", priceUSD: 54),
    ServiceItem(name: "Заміна олії у варіаторах", priceUSD: 32),
    ServiceItem(name: "Заміна сальника розподільного валу", priceUSD: 11),
    ServiceItem(name: "Ремонт турбокомпресорів", priceUSD: 360),
    ServiceItem(name: "Заміна ременя ГРМ", priceUSD: 90),
    ServiceItem(name: "Заміна приводних ременів", priceUSD: 21),
    ServiceItem(name: "Заміна ролика натягувача приводного ременя", priceUSD: 15),
    ServiceItem(name: "Заміна двигуна", priceUSD: 270),
    ServiceItem(name: "Капітальний ремонт двигуна", priceUSD: 450),
    ServiceItem(name: "Ремонт головки блоку циліндрів двигуна", priceUSD: 173),
    ServiceItem(name: "Ремонт клапанів двигуна", priceUSD: 48),
    ServiceItem(name: "Ремонт масляного насоса", priceUSD: 43),
    ServiceItem(name: "Ремонт (заміна) маховика двигуна", priceUSD: 22),
    ServiceItem(name: "Ремонт (заміна) опор двигуна", priceUSD: 11),
    ServiceItem(name: "Ремонт поршнів двигуна", priceUSD: 324),
    ServiceItem(name: "Ремонт радіаторів", priceUSD: 24),
    ServiceItem(name: "Заміна свічок запалювання", priceUSD: 3),
    ServiceItem(name: "Заміна котушок/модуля запалювання автомобіля", priceUSD: 4),
    ServiceItem(name: "Заміна високовольтних проводів", priceUSD: 11),
    ServiceItem(name: "Заміна акумулятора", priceUSD: 4),
    ServiceItem(name: "Заміна антифризу", priceUSD: 17),
    ServiceItem(name: "Заміна термостата", priceUSD: 30),
    ServiceItem(name: "Заміна помпи", priceUSD: 45),
    ServiceItem(name: "Заміна радіатора", priceUSD: 39),
    ServiceItem(name: "Чистка радіаторів системи охолодження та кондиціонера", priceUSD: 120),
    ServiceItem(name: "Чистка форсунок", priceUSD: 11),
    ServiceItem(name: "Промивка паливної системи", priceUSD: 26),
    ServiceItem(name: "Заміна паливного фільтра", priceUSD: 30),
    ServiceItem(name: "Заміна бензонасоса", priceUSD: 30),
    ServiceItem(name: "Промивка інжектора", priceUSD: 36),
    ServiceItem(name: "КПП - заміна", priceUSD: 105),
    ServiceItem(name: "КПП - ремонт", priceUSD: 180),
    ServiceItem(name: "Олія АКПП - заміна часткова (злив/затока), включаючи заміну фільтра АКПП", priceUSD: 75),
    ServiceItem(name: "Олія АКПП - заміна повна (апаратна) без заміни фільтра АКПП", priceUSD: 45),
    ServiceItem(name: "Олія АКПП - заміна повна (апаратна), включаючи заміну фільтра АКПП", priceUSD: 90),
    ServiceItem(name: "Олія МКПП - заміна", priceUSD: 12),
    ServiceItem(name: "Масло трансмісійне (міст/редуктор/роздавальна коробка) — заміна", priceUSD: 12),
    ServiceItem(name: "Зчеплення (комплект) - заміна", priceUSD: 105),
    ServiceItem(name: "Головний циліндр зчеплення - заміна", priceUSD: 30),
    ServiceItem(name: "Робочий циліндр зчеплення - заміна", priceUSD: 24),
    ServiceItem(name: "Хрестовина карданного валу - заміна", priceUSD: 39),
    ServiceItem(name: "Карданний вал - заміна", priceUSD: 24),
    ServiceItem(name: "Діагностика та заміна зчеплення", priceUSD: 105),
    ServiceItem(name: "Ремонт / заміна актуатора зчеплення", priceUSD: 65),
    ServiceItem(name: "Заміна диска зчеплення", priceUSD: 76),
    ServiceItem(name: "Заміна головного циліндра зчеплення", priceUSD: 30),
    ServiceItem(name: "Заміна зчеплення на АКПП", priceUSD: 76),
    ServiceItem(name: "Заміна троса зчеплення", priceUSD: 18),
    ServiceItem(name: "Заміна вилки зчеплення", priceUSD: 11),
    ServiceItem(name: "Заміна рідини зчеплення", priceUSD: 9),
    ServiceItem(name: "Заміна приводних валів", priceUSD: 48),
    ServiceItem(name: "Заміна ШРУС", priceUSD: 48),
    ServiceItem(name: "Заміна карданного валу", priceUSD: 24),
    ServiceItem(name: "Заміна хрестовини карданного валу", priceUSD: 39),
    ServiceItem(name: "Заміна трансмісійних рідин (міст/редуктор/роздавальна коробка)", priceUSD: 12),
    ServiceItem(name: "Заміна вихлопної системи (у зборі)", priceUSD: 45),
    ServiceItem(name: "Заміна глушника", priceUSD: 30),
    ServiceItem(name: "Заміна гофри приймальної труби", priceUSD: 39),
    ServiceItem(name: "Заміна кисневого датчика (лямбда-зонд)", priceUSD: 18),
    ServiceItem(name: "Заміна каталізатора", priceUSD: 15),
    ServiceItem(name: "Видалення каталізатора", priceUSD: 43),
    ServiceItem(name: "Заміна прокладки глушника", priceUSD: 11),
    ServiceItem(name: "Заміна труби глушника", priceUSD: 22),
    ServiceItem(name: "Діагностика та ремонт паливних форсунок", priceUSD: 11),
    ServiceItem(name: "Діагностика та ремонт ТНВД", priceUSD: 22),
    ServiceItem(name: "Заміна свічок розжарювання", priceUSD: 2),
    ServiceItem(name: "Промивка паливної системи дизельних авто", priceUSD: 48),
  ];

  static List<String> get names => items.map((e) => e.name).toList();
}
