name: core_data
description: Data sources for car info storage
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.0
  http: ^1.5.0
  shared_preferences: ^2.2.0
  timezone: ^0.10.1
  dio: ^5.4.0
  firebase_core: ^4.0.0
  get_it: ^8.2.0

core_data:
    path: ../core_data
core_repository:
    path: ../core_repository 