name: core_utils
description: Core utils package for fines_plus
version: 0.0.1
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  design_system:
    path: ../design_system
  core_repository:
    path: ../core_repository
  core_data:
    path: ../core_data
  core_services:
    path: ../core_services
  core_cubit:
    path: ../core_cubit
  core_localization:
    path: ../core_localization
  fines_plus:
    path: ../../
  flutter_bloc: ^9.1.1
  share_plus: ^11.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2

flutter:
    uses-material-design: true
